# Site settings
title: Meet Sanchit!
description: Sanchit Balchandani - @inovizz
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanchit Balchandani
user_description:
  <p>Sanchit, a skilled software engineer from Hyderabad, currently holds the position of Engineering Manager at EPAM India, where he leads the Python Discipline. With an impressive background in backend engineering, he has made significant contributions across various sectors such as healthcare, Ad Tech, E-commerce, Infrastructure, and Automation. Sanchit is particularly passionate about Infrastructure, Cloud, and SRE, while also being committed to fostering a positive work culture, empathetic people management, and supporting diversity.

In his ongoing effort to help others grow, Sanchit actively participates in the Hyderabad software community. As a co-organizer of open-source events and meetups, he collaborates with initiatives like <a
  href="https://hydpy.org/">HydPy</a> & <a href="https://dsughyd.org">DSUGHyd</a>, inspiring local tech enthusiasts to share knowledge and build meaningful connections.</p>
user_title: Open Source Enthusiast
email: sanchit@inovizz.com
twitter_username: inovizz
github_username: inovizz
linkedin_username: inovizz

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
