# Site settings
title: Meet Sanchit!
description: Sanchit Balchandani - @inovizz
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sanchit Balchandani
user_description:
  <p>Sanchit is an experienced Software Engineer based in Hyderabad and currently working as an Engineering Manager
  at EPAM India. In his current role, Sanchit is responsible for leading the Python Discipline at EPAM India. With
  extensive experience developing backend engineering projects, he has worked across diverse domains such as
  healthcare, Ad Tech, Ecommerce, Infrastructure, and Automation. His primary areas of interest include
  Infrastructure, Cloud, and SRE. Furthermore, He is actively involved in promoting the growth of the software
  community in Hyderabad, as a co-organizer of open-source communities such as <a
  href="https://hydpy.org/">HydPy</a> & <a href="https://dsughyd.org">DSUGHyd</a>.</p>
user_title: Open Source Enthusiast
email: sanchit@inovizz.com
twitter_username: inovizz
github_username: inovizz
linkedin_username: inovizz

# Google-analytics
google-analytics:
  id: ""

exclude: ["package.json", "src", "node_modules"]
